FROM us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:e87e5ef2b96893eb8b446da420f7ba7f3e3c5985 as optimism-node
FROM alpine:3.19.1

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
      apt-get -y install -y ca-certificates libssl1.1

ADD ./geth /app/geth
ADD ./geth /usr/local/bin/geth
COPY --from=optimism-node /usr/local/bin/op-node /app/op-node

ENTRYPOINT /app/geth