ARG FIREHOSE_ETHEREUM="ce9ae75"

# Build Bor in a stock Go builder container
FROM golang:1.24-alpine AS builder

RUN apk add --no-cache gcc musl-dev linux-headers git

# Get dependencies - will also be cached if we won't change go.mod/go.sum
COPY go.mod /go-ethereum/
COPY go.sum /go-ethereum/
RUN cd /go-ethereum && go mod download

ADD . /go-ethereum
RUN cd /go-ethereum && go run build/ci.go install -static ./cmd/cli/main.go

# FIXME: Actually put Firehose Ethereum when it's properly built
# Pull Bor into Firehose Core container (bor is statically linked, we can copy it from alpine to ubuntu)
FROM   ghcr.io/streamingfast/firehose-ethereum:${FIREHOSE_ETHEREUM}

COPY --from=builder /go-ethereum/build/bin/main.go /usr/local/bin/bor
RUN ln -s /usr/local/bin/bor /app/bor

EXPOSE 8545 8546 30303 30303/udp
